name: ns_player
description: NSPlayer is a HLS(.m3u8) video player for flutter. The NsPlayer is a video player that allows you to select HLS video streaming by selecting the quality.
version: 0.0.1

environment:
  sdk: ^3.2.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  auto_orientation:
    git:
      url: https://github.com/Marco4763/auto_orientation.git
      ref: agp_compatibility
  path_provider: ^2.1.4
#  flutter_screen_wake: ^1.0.2
  video_player: ^2.8.1
  wakelock_plus: ^1.1.6
  audio_video_progress_bar: ^2.0.3
#  flutter_downloader: ^1.9.1
  path: ^1.8.3
  flutter_lints: ^4.0.0
  flutter_svg: 2.0.10+1

dependency_overrides:
  flutter:
    sdk: flutter
  video_player_android: ^2.4.17

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/icons/
    - assets/images/

